# <h1><center> HomeWork - 2</center></h1>
## <center>By : Nitika</center>

 ## Q1: Create matrix A with size(3,5) containing random numbers

In [44]:
import numpy as np

A = np.random.randint(20,size=(3,5))

print("Matrix with random numbers\n",A)

Matrix with random numbers
 [[ 1 19  0  4 14]
 [ 3  6 19  0 14]
 [10 16  1 15 17]]


## Q2: Find the size and length of martix A.

In [45]:
print("Size of matrix A: \t",A.size)

Size of matrix A: 	 15


In [46]:
print("Length of matrix A: \t",len(A))

Length of matrix A: 	 3


## Q3: Resize(crop/slice) matrix A to size (3x4).

In [47]:
print("Matrix A after resizing to 3x4 size :\n")
A.resize(3,4)
print(A)

Matrix A after resizing to 3x4 size :

[[ 1 19  0  4]
 [14  3  6 19]
 [ 0 14 10 16]]


## Q4: Find the transpose of matrix A and assign it to B.

In [83]:
B = A.T
print("Transpose of matrix A :\n", B)

Transpose of matrix A :
 [[ 1 14  0]
 [19  3 14]
 [ 0  6 10]
 [ 4 19 16]]


## Q5: Find the minimum  value in column 1 of matrix B.

In [49]:
print("Minimum  value in column 1 of matrix B :\t",B.min(axis=0)[0])

Minimum  value in column 1 of matrix B :	 0


In [52]:
print("Minimum  value in column 1 of matrix B :\t",min(B[:,0]))

Minimum  value in column 1 of matrix B :	 0


## Q6: Find the minimum and maximum value for the entire matrix A.

In [53]:
print("Minimum  value in martix A :\t",A.min())

Minimum  value in martix A :	 0


In [54]:
print("Maximum  value in martix A :\t",A.max())

Maximum  value in martix A :	 19


## Q7:Create vector (an array) X with 4 random numbers.

In [55]:
X = np.random.randint(1,100,4)

print("Array X with 4 random numbers : \n\n", X)

Array X with 4 random numbers : 

 [97 71 78 36]


## Q8: Create a function and pass vector X and matrix A in it and then multiple vector X with matrix A and assign the result in D.

In [75]:
def multiplication(v,m):
    d = v.dot(m.T)
    return d

In [77]:
D = multiplication(X,A)
print(D)

[1590 2723 2350]


## Q9: Create a complex number Z with absolute and real part !=0.

In [70]:
import cmath

Z = complex(3,5)

print("Complex number Z : \t", Z)

Complex number Z : 	 (3+5j)


## Q10: Show the real and imaginary part as well as it's absolute  value.

In [73]:
real = Z.real
imag = Z.imag
absoluteValue = abs(Z)
print("Real part is : \t", real)
print("Imaginary part is : \t", imag)
print("Absolute value is : \t", absoluteValue)

Real part is : 	 3.0
Imaginary part is : 	 5.0
Absolute value is : 	 5.830951894845301


## Q11: Multiple result D with absolute value of Z and  record it to C.

In [79]:
C = D * absoluteValue

print(C)

[ 9271.2135128  15877.68200966 13702.73695289]


## Q12: Convert matrix B from a matrix to a string and overwrite B.

In [86]:
B = [[str(i) for i in ele] for ele in B]
print(B)

[['1', '14', '0'], ['19', '3', '14'], ['0', '6', '10'], ['4', '19', '16']]


## Q13: Display a text on screen "[Name] is done with HW2", but pass your name as a string variable.

In [80]:
name = "Nitika"

In [81]:
print(name," is done with HomeWork 2!!")

Nitika  is done with HomeWork 2!!
